# https://hub.docker.com/_/php/
FROM php:7.2-apache

COPY src/ /var/www/html/

# docker run -d -p 9090:80 php:7.2-apache
# -d pour tourner en background
# -p port mapping

# docker ps pour voir les images qui tournent
# obetnir son ip: hostname -I
# telnet telnet 172.17.0.1 9090
# envoi de requete http au serveur
# GET / HTTP1.0
# bien sur on est denied

# docker inspect lenomducontainer(docker ps)
# info du container, chercher le champ "IPAddress:"
# "IPAddress": "172.17.0.2"
